### ISSUE TITLE
kSha, GYan and SRI displaying junk

### ISSUE THREAD

**Issue by nsesha92** [avinash311/itrans#3]
With the default mapping table, the following input code is displaying junk/????

SRI

**Comment by avinash311** [comment]
It displays nothing - not junk.
The spreadsheet has blanks for the SRI row. If you know of a unicode character or sequence that represents SRI, let me know and I can update the aczoom.com/itrans/online input.

kSha GYa  and work fine. Tested on a Windows 10 computer.

**Comment by nsesha92** [comment]
Thanks for looking into this.

For SRI, if you input shrii, it displays properly.
So the sequence is {sha}{consonants-joiner}{ra}{dv-ii}

Instead of hardcoding, better to use sequence for kSha & GYa also:

kSha - {ka}{consonants-joiner}{ssa}{dv-a}
GYa - {ja}{consonants-joiner}{nya}{dv-a}

**Comment by nsesha92** [comment]
SRI for Tamil, the same sequence  {sha}{consonants-joiner}{ra}{dv-ii}  works fine. 
So this sequence is common for all languages.

Also Grantha OM code is u+11350.

**Comment by avinash311** [comment]
Thanks - I've updated the default spreadsheet to use
SRI ->     {sha}{consonants-joiner}{ra}{dv-ii} for all scripts
OM (Grantha) ->   𑍐
I've not updated the script yet - so the online site won't use those for a week or two until the next release.
But - see the other comment about changing the eEoO coding and using load custom spreadsheet which would fix that issue too.

The others (kSha, GYa) I left alone since they work fine on both Windows and Linux (Chrome browser).
Which computer + browser are you using that is not displaying those characters?

**Comment by nsesha92** [comment]
Ok Thanks. Please do drop a note when you do the next release so that I can check it.

I am using Crome+Win10 laptop.

As such no issues with kSha, GYa. But going by the std notation/convention used, I thought its better to use Unicode or Command line for all line items.

**Comment by avinash311** [comment]
Fixed.

**Comment by nsesha92** [comment]
Not sure if you have updated the script.

But for Hindi, **for all others**, including hardcoded **Tamil**, displaying with halanta/virama.

श्री्‌  ,   ஶ்ரீ்‌,   શ્રી્‌   ,  𑘫𑘿𑘨𑘲 and so on.

Roman is correct - śrī

Unicode names: {shrii}{end-word-vowel}

Something to do with end-word-vowel / schwa deletion?

**Comment by avinash311** [comment]
Yes, SRI should not be tagged as consonant (which causes the end-word-vowel / schw-deletion). Now fixed.
